import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./_component/NavBar/NavBar";
import { Toaster } from "react-hot-toast";
import ContextProvider from "./context/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "IT LOGIKO Job - Task",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ContextProvider>
          <Toaster />
          <NavBar />
          {children}
        </ContextProvider>
      </body>
    </html>
  );
}
